// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8vP663QjQMHfzbh3ScxAvcIhOjboCXtQ',
    appId: '1:645325496237:web:4b7b279e9c7b4860b10b24',
    messagingSenderId: '645325496237',
    projectId: 'project-7ec73',
    authDomain: 'project-7ec73.firebaseapp.com',
    databaseURL: 'https://project-7ec73-default-rtdb.firebaseio.com',
    storageBucket: 'project-7ec73.firebasestorage.app',
    measurementId: 'G-99SETR6EW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC19g1T1Up-_zsNzaYFkUg-diZHAUv_Yfw',
    appId: '1:645325496237:android:06b39943b5db0c70b10b24',
    messagingSenderId: '645325496237',
    projectId: 'project-7ec73',
    databaseURL: 'https://project-7ec73-default-rtdb.firebaseio.com',
    storageBucket: 'project-7ec73.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8vP663QjQMHfzbh3ScxAvcIhOjboCXtQ',
    appId: '1:645325496237:web:0b7660b8990cf6f2b10b24',
    messagingSenderId: '645325496237',
    projectId: 'project-7ec73',
    authDomain: 'project-7ec73.firebaseapp.com',
    databaseURL: 'https://project-7ec73-default-rtdb.firebaseio.com',
    storageBucket: 'project-7ec73.firebasestorage.app',
    measurementId: 'G-ENX1JP3LKT',
  );

}